#!/bin/sh

getLayout() {
    setxkbmap -query | awk '/layout/{print $2}'
}
CURRENTKB="$(getLayout)"

switchLayout() {
    if test "$CURRENTKB" = "is"
    then
        setxkbmap us
    else
        setxkbmap is
    fi
    setxkbmap -option caps:escape
}

case $BLOCK_BUTTON in
  1) switchLayout
esac

getLayout

