local harpoon = require("harpoon")
vim.keymap.set("n", "<leader>a", function()
	harpoon:list():add()
end, { desc = "[A]dd current file to harpoon list" })
vim.keymap.set("n", "<C-s>", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "[S]earch harpoon list" })

vim.keymap.set("n", "<C-n>", function()
	harpoon:list():select(1)
end, { desc = "Go to 1st harpooned file" })
vim.keymap.set("n", "<C-e>", function()
	harpoon:list():select(2)
end, { desc = "Go to 2nd harpooned file" })
vim.keymap.set("n", "<C-i>", function()
	harpoon:list():select(3)
end, { desc = "Go to 3rd harpooned file" })

-- Toggle previous & next buffers stored within Harpoon list
vim.keymap.set("n", "<C-S-P>", function()
	harpoon:list():prev()
end, { desc = "Go to [P]revious harpooned file" })
vim.keymap.set("n", "<C-S-N>", function()
	harpoon:list():next()
end, { desc = "Go to [N]ext harpooned file" })
